### ISSUE TITLE
Format of file generated by python3 passwords.py > passwd

### ISSUE THREAD

**Issue by rei-vilo** [tinkerthon/passwordvault#1]
Hi!

Thank you for sharing this project.

I am not using `pass` but another passwords manager. 

Could you please provide an example of the file generated by `python3 passwords.py > passwd` and encrypted by `python3 encrypt.py`?

Thank you!

**Comment by oschettler** [comment]
Hi, I have added a short example password file `example.txt`. You can encrypt it, using the `env.example` master password, like so:

````
python3 encrypt.py example.txt > crypted-example.txt
````

**Comment by rei-vilo** [comment]
Thank you!
