### ISSUE TITLE
How do I change my master password?

### ISSUE THREAD

**Issue by naosone** [tinkerthon/passwordvault#3]
Thank you for sharing your nice project.

I tried passwordvault-v1.10.uf2 at once, however I could not unlock my "crypted.txt".
Is the master password of passwordvalult fixed at compile time?

**Comment by oschettler** [comment]
Hi naosone,
thank you for trying this out. 
You are right. Obviously, with the master password being a compile time option, the current UF2 file makes no sense. I will see if I can find a quick fix and create an update today.
-- Olav

**Comment by oschettler** [comment]
I have create a new release 1.11 which fixes the compile-time dependency.
Thanks again for bringing this up
